# Boilerplate Code for Releasing Using Auto by Intuit
# Follow this beforehand: https://intuit.github.io/auto/docs/welcome/getting-started
# Modify Parts to Suit Needs

name: Release EngLang Compiler

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
          
      - name: Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y zip wget
          
      - name: Zip Everything
        run: |
          # Create dist folder if it doesn't exist
          mkdir -p dist

          # .zip the files with exclusion
          zip -r dist/EngLang-Compiler.zip . -x "README.md" "assets/*" ".github/*" ".git/*" ".gitignore" ".autorc" "dist/*" ".vscode/*" "example/*"
          
      - name: Clone Auto Package.json
        run: |
          # Download Auto Package.json
          wget "https://raw.githubusercontent.com/MostlyWhat/.github/main/assets/auto/package.json"

          # Download Auto Package-lock.json
          wget "https://raw.githubusercontent.com/MostlyWhat/.github/main/assets/auto/package-lock.json"

          ls

      - name: Install dependencies
        run: npm ci

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Create Release
        run: |
          npx auto shipit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.GH_PAT }}
