name: Release 

on: [push]

jobs:
  release:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Install zip
        run: |
          choco install zip -y

      - name: Zip Everything
        run: |
          # Create dist folder if it doesn't exist
          mkdir -p dist

          # .zip the files with exclusion
          zip -r dist/EngLang-Compiler.zip . -x README.md -x assets/\* -x .github/\* -x .git/\* -x .gitignore

      - name: Get Latest Release
        shell: powershell
        run: |
          $url = "https://api.github.com/repos/intuit/auto/releases/latest"
          $response = Invoke-RestMethod $url
          $LATEST_RELEASE = $response.tag_name
          echo "::set-env name=LATEST_RELEASE::$LATEST_RELEASE"

      - name: Download Latest Release
        run: |
          # Get latest release from environment variable
          LATEST_RELEASE=$env:LATEST_RELEASE
          echo "Latest release is $LATEST_RELEASE"

          # Download auto-win.exe.gz
          wget "https://github.com/intuit/auto/releases/download/$LATEST_RELEASE/auto-win.exe.gz"

          # Extract auto-win.exe.gz
          tar -xf auto-win.exe.gz

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./auto.exe shipit